# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c86d2b889358c151d13fd6e8b50e90b666e2e8ee6c97c83bc1a0b732a8a3c37cd31437cbd220772817ede95a08f8af429ada1754af65219d256d4d1fe649afc3

test:
  secret_key_base: 32cbc1476fcb2bf6ea3feca6b6b9681f757d94015f8fec66f3ba7071250111457dfe3fb566f8459258efc48d06c4462d316df5d06ca5ab4ffe89b054e3115cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
